### ISSUE TITLE
sort2/img/plot.pdf 

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/jPerturb-experiments#11]
rename sort2 in quicksort-visualization
rename in perturbationVisualization.pdf
X-axis in #calls (and not depth of call)
legend is precise: Add1@524iteration@Loc532#1
AddRnd@Loc18#789

number **o**f unsorted pair**s**

long caption below the figure, say the size of the array to be sorted
add the %success of this location

**Comment by danglotb** [comment]
I'm working on a better log system, in order to have a precise legend. It will allow to do the heat map too.
