### ISSUE TITLE
X_per_location_y

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/jPerturb-experiments#17]
rename #enactions as #perturbations
add column #tasks (#tasks < #enactions if several perturbations by task) 
add column avg_perturbations_by_task

**Comment by monperrus** [comment]
if #perturb = 0 -> %success = N/A (and not 100%)

**Comment by monperrus** [comment]
remove #call

add #call_all_execs (reference run non perturbed)
add avg_call_per_execs (reference run non perturbed)

**Comment by danglotb** [comment]
we must review columns, because it's look like I misunderstand :

```
add column #tasks (#tasks < #enactions if several perturbations by task)
add column avg_perturbations_by_task
```

#Tasks -> #Execs

**Comment by danglotb** [comment]
AddOne and AddN, 
add #ExecRef

and reformat all logs
