### ISSUE TITLE
simplex oracle

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/jPerturb-experiments#23]
check all variables of the problem

**Comment by danglotb** [comment]
The function optimize() of SimplexSolver return a PointValuePair. We can read from javadoc : 

> This class holds a point and the value of an objective function at that point.

So the method getValue() return the value of the objective function (One of the OptimizationData). The oracle assert this value with the unpertubed execution, and then assert if the point (hold by the PointValuePair class too) respect LinearConstraints.
